import os
import sys
import logging
from datetime import datetime, UTC

# Add root directory to sys.path to allow importing 'config'
root_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
if root_path not in sys.path:
    sys.path.insert(0, root_path)

from typing import Dict, Any

# PDF Imports
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem, PageBreak, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor, lightgrey, white, black
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

# DOCX Imports
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

# Config Import
from config import CONFIG

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Languages Mapping
LANGUAGES_MAP = {
    'en': 'English',
    'ta': 'Tamil',
    'hi': 'Hindi',
    'te': 'Telugu',
    'kn': 'Kannada',
    'ml': 'Malayalam',
    'bn': 'Bengali',
    'mr': 'Marathi',
    'gu': 'Gujarati',
    'pa': 'Punjabi',
    'ur': 'Urdu'
}

# Register Unicode fonts for ReportLab if running on Windows
def register_unicode_fonts():
    font_name = 'Helvetica'
    bold_font_name = 'Helvetica-Bold'
    
    font_path = r"C:\Windows\Fonts\Nirmala.ttc"
    if os.path.exists(font_path):
        try:
            from reportlab.pdfbase import pdfmetrics
            from reportlab.pdfbase.ttfonts import TTFont
            # Attempt to register proper Regular (index 0) and Bold (index 1) sub-fonts
            try:
                pdfmetrics.registerFont(TTFont('Nirmala', font_path, subfontIndex=0))
                pdfmetrics.registerFont(TTFont('Nirmala-Bold', font_path, subfontIndex=1))
            except Exception as ttc_err:
                logger.warning(f"Could not load TTC indices, loading default: {ttc_err}")
                pdfmetrics.registerFont(TTFont('Nirmala', font_path))
                pdfmetrics.registerFont(TTFont('Nirmala-Bold', font_path))
            font_name = 'Nirmala'
            bold_font_name = 'Nirmala-Bold'
        except Exception as e:
            logger.warning(f"Error registering Nirmala font for PDF: {e}")
            
    return font_name, bold_font_name


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and print 'Page X of Y' footers."""
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # Check if Unicode font is registered
        font_name = 'Helvetica'
        try:
            from reportlab.pdfbase import pdfmetrics
            if 'Nirmala' in pdfmetrics.getRegisteredFontNames():
                font_name = 'Nirmala'
        except:
            pass
            
        self.setFont(font_name, 8)
        self.setFillColor(HexColor("#64748B")) # Slate-500
        
        # Draw running header on page 2 and later
        if self._pageNumber > 1:
            self.drawString(54, 755, "LECTA AI — Lecture Notes")
            self.setStrokeColor(HexColor("#E2E8F0")) # Slate-200 divider
            self.setLineWidth(0.5)
            self.line(54, 750, 612 - 54, 750)
            
        # Draw running footer line and info on all pages
        self.setStrokeColor(HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 50, 612 - 54, 50)
        
        self.drawString(54, 38, "Generated by LECTA AI")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(612 - 54, 38, page_text)
        
        self.restoreState()


def export_as_pdf(session_data: Dict[str, Any], output_path: str) -> str:
    """Generates a structured, premium styled PDF lecture notes document."""
    logger.info(f"Generating PDF for session {session_data.get('session_id')} at {output_path}")
    
    # Establish margins at 0.75 inch (54 points)
    doc = SimpleDocTemplate(
        output_path, 
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Register and setup font
    font_name, bold_font_name = register_unicode_fonts()
    
    # Colors
    PRIMARY_COLOR = HexColor('#4F46E5')    # Indigo 600
    TEXT_DARK = HexColor('#0F172A')        # Slate 900
    TEXT_MUTED = HexColor('#475569')       # Slate 600
    
    # Custom Styles
    title_app_style = ParagraphStyle(
        name='TitleApp',
        fontName=bold_font_name,
        fontSize=9.5,
        leading=11,
        textColor=HexColor('#818CF8'), # Indigo 400
        textTransform='uppercase',
        spaceAfter=3
    )
    
    title_lecture_style = ParagraphStyle(
        name='TitleLecture',
        fontName=bold_font_name,
        fontSize=18,
        leading=22,
        textColor=white,
        spaceAfter=5
    )
    
    meta_style = ParagraphStyle(
        name='MetaStyle',
        fontName=font_name,
        fontSize=8,
        leading=10,
        textColor=HexColor('#94A3B8') # Slate 400
    )
    
    heading1_style = ParagraphStyle(
        name='CustomHeading1',
        fontName=bold_font_name,
        fontSize=12.5,
        leading=15,
        textColor=TEXT_DARK,
        spaceBefore=12,
        spaceAfter=5,
        keepWithNext=True
    )
    
    heading2_style = ParagraphStyle(
        name='CustomHeading2',
        fontName=bold_font_name,
        fontSize=10,
        leading=12,
        textColor=HexColor('#1E293B'),
        spaceBefore=8,
        spaceAfter=3,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        name='CustomBody',
        fontName=font_name,
        fontSize=9.5,
        leading=13.5,
        textColor=HexColor('#1E293B'),
        spaceAfter=5
    )
    
    bullet_style = ParagraphStyle(
        name='CustomBullet',
        fontName=font_name,
        fontSize=9.5,
        leading=13.5,
        textColor=HexColor('#1E293B'),
        spaceAfter=3
    )
    
    question_style = ParagraphStyle(
        name='QuestionStyle',
        fontName=bold_font_name,
        fontSize=9.5,
        leading=13,
        textColor=HexColor('#312E81'), # Indigo 900
        spaceBefore=4,
        spaceAfter=1.5,
        keepWithNext=True
    )
    
    answer_style = ParagraphStyle(
        name='AnswerStyle',
        fontName=font_name,
        fontSize=9.5,
        leading=13,
        textColor=TEXT_MUTED,
        leftIndent=15,
        spaceAfter=4
    )
    
    # Update stylesheet to use Unicode-capable fonts
    for style_name in list(styles.byName.keys()):
        style = styles[style_name]
        if hasattr(style, 'fontName'):
            orig_font = style.fontName or ""
            if "Bold" in orig_font:
                style.fontName = bold_font_name
            else:
                style.fontName = font_name
            
    story = []
    
    # Header Banner Card
    filename = session_data.get('filename', 'Unknown')
    gen_date = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S")
    detected_lang = session_data.get('language', {}).get('name', 'Not available')
    target_lang_code = session_data.get('target_language')
    target_lang = LANGUAGES_MAP.get(target_lang_code, target_lang_code).upper() if target_lang_code else 'Not available'
    session_id = session_data.get('session_id', 'N/A')
    
    banner_data = [
        [Paragraph("LECTA AI - Lecture Notes System", title_app_style)],
        [Paragraph(filename, title_lecture_style)],
        [Paragraph(f"<b>Session ID:</b> {session_id} &nbsp;|&nbsp; <b>Generated:</b> {gen_date} &nbsp;|&nbsp; <b>Detected:</b> {detected_lang} &nbsp;|&nbsp; <b>Target:</b> {target_lang}", meta_style)]
    ]
    banner_table = Table(banner_data, colWidths=[doc.width])
    banner_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), HexColor('#1E293B')), # Premium Slate 800 background
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 16),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 16),
        ('LEFTPADDING', (0, 0), (-1, -1), 20),
        ('RIGHTPADDING', (0, 0), (-1, -1), 20),
    ]))
    story.append(banner_table)
    story.append(Spacer(1, 15))
    
    # Left-Accent section headers (Notion style)
    def create_section_header(title_text):
        header_para = Paragraph(f"<b>{title_text}</b>", heading1_style)
        header_table = Table([["", header_para]], colWidths=[4, doc.width - 12])
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, 0), PRIMARY_COLOR), # Left bar gets primary color
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (1, 0), (1, 0), 8),
            ('RIGHTPADDING', (1, 0), (1, 0), 0),
            ('LEFTPADDING', (0, 0), (0, 0), 0),
            ('RIGHTPADDING', (0, 0), (0, 0), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 1),
            ('TOPPADDING', (0, 0), (-1, -1), 1),
        ]))
        return header_table

    # Styled callout box (using ParagraphStyle to support page splitting)
    def create_callout_box(text, bg_hex_color, border_hex_color, name_prefix="Callout"):
        formatted_text = (text or "").replace('\n', '<br/>')
        box_style = ParagraphStyle(
            name=f"{name_prefix}_{bg_hex_color.replace('#', '')}",
            fontName=font_name,
            fontSize=9.5,
            leading=13.5,
            textColor=HexColor('#1E293B'),
            backColor=HexColor(bg_hex_color),
            borderColor=HexColor(border_hex_color),
            borderWidth=0.5,
            borderPadding=12,
            spaceAfter=15
        )
        return Paragraph(formatted_text, box_style)

    # Section: Summary
    story.append(create_section_header("Summary"))
    story.append(Spacer(1, 8))
    summary_text = session_data.get('summary') or "Not available"
    story.append(create_callout_box(summary_text, '#F8FAFC', '#E2E8F0')) # Slate-50 / Slate-200
    story.append(Spacer(1, 15))
    
    # Section: Key Points
    story.append(create_section_header("Key Points"))
    story.append(Spacer(1, 8))
    bullet_notes = session_data.get('bullet_notes')
    if bullet_notes:
        items = []
        for note in bullet_notes:
            cleaned_note = note.replace('• ', '').strip()
            p = Paragraph(f"• &nbsp;{cleaned_note}", bullet_style)
            items.append(p)
            items.append(Spacer(1, 4))
        story.extend(items)
    else:
        story.append(Paragraph("Not available", body_style))
    story.append(Spacer(1, 12))
    

    
    # Section: Translation
    story.append(create_section_header(f"Translation ({target_lang})"))
    story.append(Spacer(1, 8))
    translation = session_data.get('translated_content') or "Not available"
    story.append(create_callout_box(translation, '#F5F3FF', '#DDD6FE')) # Violet-50 / Violet-200
    story.append(Spacer(1, 15))
    
    # Section: Exam Questions
    story.append(create_section_header("Exam Questions & Answers"))
    story.append(Spacer(1, 8))
    questions = session_data.get('questions', [])
    if questions:
        q_types = {'definition': 'Definitions', 'fill_blank': 'Fill in the Blanks', 'true_false': 'True or False'}
        for q_type, q_label in q_types.items():
            type_qs = [q for q in questions if q['type'] == q_type]
            if type_qs:
                story.append(Paragraph(f"<u>{q_label}</u>", heading2_style))
                story.append(Spacer(1, 4))
                for q in type_qs:
                    story.append(Paragraph(f"<b>Q:</b> {q['question']}", question_style))
                    story.append(Paragraph(f"<b>A:</b> {q['answer']}", answer_style))
                    story.append(Spacer(1, 4))
    else:
        story.append(Paragraph("Not available", body_style))
    
    # Compile document using our premium NumberedCanvas
    try:
        doc.build(story, canvasmaker=NumberedCanvas)
    except Exception as e:
        logger.error(f"Failed to build PDF with primary fonts: {e}. Retrying with sanitized text...")
        
        # Override fonts to standard Helvetica
        font_name = 'Helvetica'
        bold_font_name = 'Helvetica-Bold'
        
        # Clear story
        story = []
        
        # Helper function to sanitize any string to safe ASCII representation to avoid ReportLab crashes
        def sanitize(text_val):
            if not text_val:
                return ""
            if not isinstance(text_val, str):
                return str(text_val)
            # Encode and ignore non-ascii characters to ensure Helvetica never crashes
            return text_val.encode('ascii', errors='ignore').decode('ascii')
            
        # Re-build banner data using sanitized safe strings
        sanitized_filename = sanitize(filename)
        sanitized_detected = sanitize(detected_lang)
        sanitized_target = sanitize(target_lang)
        
        banner_data = [
            [Paragraph("LECTA AI - Lecture Notes System", title_app_style)],
            [Paragraph(sanitized_filename, title_lecture_style)],
            [Paragraph(f"<b>Session ID:</b> {session_id} &nbsp;|&nbsp; <b>Generated:</b> {gen_date} &nbsp;|&nbsp; <b>Detected:</b> {sanitized_detected} &nbsp;|&nbsp; <b>Target:</b> {sanitized_target}", meta_style)]
        ]
        banner_table = Table(banner_data, colWidths=[doc.width])
        banner_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), HexColor('#1E293B')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 16),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 16),
            ('LEFTPADDING', (0, 0), (-1, -1), 20),
            ('RIGHTPADDING', (0, 0), (-1, -1), 20),
        ]))
        story.append(banner_table)
        story.append(Spacer(1, 15))
        
        # Summary
        story.append(create_section_header("Summary"))
        story.append(Spacer(1, 8))
        story.append(create_callout_box(sanitize(session_data.get('summary') or "Not available"), '#F8FAFC', '#E2E8F0'))
        story.append(Spacer(1, 15))
        
        # Key Points
        story.append(create_section_header("Key Points"))
        story.append(Spacer(1, 8))
        bullet_notes = session_data.get('bullet_notes')
        if bullet_notes:
            items = []
            for note in bullet_notes:
                cleaned_note = note.replace('• ', '').strip()
                p = Paragraph(f"• &nbsp;{sanitize(cleaned_note)}", bullet_style)
                items.append(p)
                items.append(Spacer(1, 4))
            story.extend(items)
        else:
            story.append(Paragraph("Not available", body_style))
        story.append(Spacer(1, 12))
        

        
        # Translation
        story.append(create_section_header(f"Translation ({sanitized_target})"))
        story.append(Spacer(1, 8))
        story.append(create_callout_box(sanitize(session_data.get('translated_content') or "Not available"), '#F5F3FF', '#DDD6FE'))
        story.append(Spacer(1, 15))
        
        # Exam Questions
        story.append(create_section_header("Exam Questions & Answers"))
        story.append(Spacer(1, 8))
        questions = session_data.get('questions', [])
        if questions:
            q_types = {'definition': 'Definitions', 'fill_blank': 'Fill in the Blanks', 'true_false': 'True or False'}
            for q_type, q_label in q_types.items():
                type_qs = [q for q in questions if q['type'] == q_type]
                if type_qs:
                    story.append(Paragraph(f"<u>{q_label}</u>", heading2_style))
                    story.append(Spacer(1, 4))
                    for q in type_qs:
                        story.append(Paragraph(f"<b>Q:</b> {sanitize(q['question'])}", question_style))
                        story.append(Paragraph(f"<b>A:</b> {sanitize(q['answer'])}", answer_style))
                        story.append(Spacer(1, 4))
        else:
            story.append(Paragraph("Not available", body_style))
            
        # Re-map styles to Helvetica to guarantee it compiles
        for style_name in list(styles.byName.keys()):
            style = styles[style_name]
            if hasattr(style, 'fontName'):
                if "Bold" in (style.fontName or ""):
                    style.fontName = 'Helvetica-Bold'
                else:
                    style.fontName = 'Helvetica'
                    
        title_app_style.fontName = 'Helvetica-Bold'
        title_lecture_style.fontName = 'Helvetica-Bold'
        meta_style.fontName = 'Helvetica'
        heading1_style.fontName = 'Helvetica-Bold'
        heading2_style.fontName = 'Helvetica-Bold'
        body_style.fontName = 'Helvetica'
        bullet_style.fontName = 'Helvetica'
        question_style.fontName = 'Helvetica-Bold'
        answer_style.fontName = 'Helvetica'
        
        doc.build(story, canvasmaker=NumberedCanvas)
        
    return output_path


def set_cell_background(cell, hex_color):
    """Sets background shading of a DOCX table cell."""
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'), 'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'), hex_color)
    tcPr.append(shd)

def set_cell_margins(cell, top=140, bottom=140, left=200, right=200):
    """Sets cell padding (margins) of a DOCX table cell in twentieths of a point (dxa)."""
    tcPr = cell._tc.get_or_add_tcPr()
    tcMar = OxmlElement('w:tcMar')
    for margin_name, val in [('w:top', top), ('w:bottom', bottom), ('w:left', left), ('w:right', right)]:
        node = OxmlElement(margin_name)
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tcMar.append(node)
    tcPr.append(tcMar)


def export_as_docx(session_data: Dict[str, Any], output_path: str) -> str:
    """Generates a structured, premium styled Word document (DOCX)."""
    logger.info(f"Generating DOCX for session {session_data.get('session_id')} at {output_path}")
    
    doc = Document()
    
    # Configure page margins to 1 inch all around
    for section in doc.sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)
        
    # Set default Normal font style
    normal_style = doc.styles['Normal']
    normal_font = normal_style.font
    normal_font.name = 'Segoe UI'
    normal_font.size = Pt(10.5)
    normal_font.color.rgb = RGBColor(15, 23, 42) # Slate 900
    
    # Modern Title Block
    title_para = doc.add_paragraph()
    title_run = title_para.add_run("LECTA AI — Lecture Notes")
    title_run.font.name = 'Segoe UI Semibold'
    title_run.font.size = Pt(20)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(79, 70, 229) # Indigo 600
    title_para.paragraph_format.space_after = Pt(12)
    
    filename = session_data.get('filename', 'Unknown')
    gen_date = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S")
    detected_lang = session_data.get('language', {}).get('name', 'Not available')
    target_lang_code = session_data.get('target_language')
    target_lang = LANGUAGES_MAP.get(target_lang_code, target_lang_code).upper() if target_lang_code else 'Not available'
    session_id = session_data.get('session_id', 'N/A')
    
    # Metadata Box (Borderless Table)
    meta_table = doc.add_table(rows=3, cols=2)
    meta_table.autofit = True
    
    fields_left = [
        ("File Name:", filename),
        ("Generated:", gen_date),
        ("Session ID:", session_id)
    ]
    fields_right = [
        ("Detected Language:", detected_lang),
        ("Target Language:", target_lang),
        ("", "")
    ]
    
    for i, (lbl, val) in enumerate(fields_left):
        cell = meta_table.rows[i].cells[0]
        p = cell.paragraphs[0]
        run_lbl = p.add_run(lbl + " ")
        run_lbl.bold = True
        run_lbl.font.size = Pt(9)
        run_lbl.font.color.rgb = RGBColor(71, 85, 105)
        run_val = p.add_run(val)
        run_val.font.size = Pt(9)
        run_val.font.color.rgb = RGBColor(71, 85, 105)
        
    for i, (lbl, val) in enumerate(fields_right):
        if not lbl:
            continue
        cell = meta_table.rows[i].cells[1]
        p = cell.paragraphs[0]
        run_lbl = p.add_run(lbl + " ")
        run_lbl.bold = True
        run_lbl.font.size = Pt(9)
        run_lbl.font.color.rgb = RGBColor(71, 85, 105)
        run_val = p.add_run(val)
        run_val.font.size = Pt(9)
        run_val.font.color.rgb = RGBColor(71, 85, 105)
        
    # Spacer
    spacer = doc.add_paragraph()
    spacer.paragraph_format.space_before = Pt(8)
    
    # Custom Heading builder
    def add_custom_heading(text, level=1):
        p = doc.add_paragraph()
        run = p.add_run(text)
        run.bold = True
        if level == 1:
            run.font.size = Pt(14)
            run.font.color.rgb = RGBColor(15, 23, 42) # Slate 900
            p.paragraph_format.space_before = Pt(16)
            p.paragraph_format.space_after = Pt(6)
        else:
            run.font.size = Pt(11.5)
            run.font.color.rgb = RGBColor(51, 65, 85) # Slate 700
            p.paragraph_format.space_before = Pt(10)
            p.paragraph_format.space_after = Pt(4)
        p.paragraph_format.keep_with_next = True
        return p
        
    # Helper to add styled callout tables
    def add_callout_box(text, bg_hex):
        tbl = doc.add_table(rows=1, cols=1)
        tbl.alignment = 1 # Center
        cell = tbl.cell(0, 0)
        set_cell_background(cell, bg_hex)
        set_cell_margins(cell, top=140, bottom=140, left=200, right=200)
        p = cell.paragraphs[0]
        run = p.add_run(text)
        run.font.size = Pt(10)
        p.paragraph_format.space_after = Pt(0)
        # Spacer paragraph after
        spacer = doc.add_paragraph()
        spacer.paragraph_format.space_before = Pt(4)

    # Summary
    add_custom_heading("Summary", level=1)
    add_callout_box(session_data.get('summary') or "Not available", "F8FAFC")
    
    # Key Points
    add_custom_heading("Key Points", level=1)
    bullet_notes = session_data.get('bullet_notes')
    if bullet_notes:
        for note in bullet_notes:
            cleaned_note = note.replace('• ', '').strip()
            p = doc.add_paragraph(style='List Bullet')
            run = p.add_run(cleaned_note)
            p.paragraph_format.space_after = Pt(4)
    else:
        doc.add_paragraph("Not available")
        

        
    # Translation
    add_custom_heading(f"Translation ({target_lang})", level=1)
    add_callout_box(session_data.get('translated_content') or "Not available", "F5F3FF")
    
    # Exam Questions
    add_custom_heading("Exam Questions & Answers", level=1)
    questions = session_data.get('questions', [])
    if questions:
        q_types = {'definition': 'Definitions', 'fill_blank': 'Fill in the Blanks', 'true_false': 'True or False'}
        for q_type, q_label in q_types.items():
            type_qs = [q for q in questions if q['type'] == q_type]
            if type_qs:
                add_custom_heading(q_label, level=2)
                for q in type_qs:
                    qp = doc.add_paragraph()
                    qrun = qp.add_run(f"Q: {q['question']}")
                    qrun.font.bold = True
                    qrun.font.color.rgb = RGBColor(49, 46, 129) # Deep indigo
                    qp.paragraph_format.space_before = Pt(4)
                    qp.paragraph_format.space_after = Pt(2)
                    qp.paragraph_format.keep_with_next = True
                    
                    ap = doc.add_paragraph()
                    arun = ap.add_run(f"A: {q['answer']}")
                    arun.font.italic = True
                    arun.font.color.rgb = RGBColor(71, 85, 105) # Muted Slate
                    ap.paragraph_format.left_indent = Inches(0.2)
                    ap.paragraph_format.space_after = Pt(6)
    else:
        doc.add_paragraph("Not available")
        
    doc.save(output_path)
    return output_path

def export_as_txt(session_data: Dict[str, Any], output_path: str) -> str:
    """Generates a structured plain text file (TXT)."""
    logger.info(f"Generating TXT for session {session_data.get('session_id')} at {output_path}")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("=== LECTURE NOTES ===\n")
        f.write(f"File: {session_data.get('filename', 'Unknown')}\n")
        f.write(f"Generated: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Session ID: {session_data.get('session_id', 'N/A')}\n\n")
        
        f.write("=== SUMMARY ===\n")
        f.write((session_data.get('summary') or "Not available") + "\n\n")
        
        f.write("=== KEY POINTS ===\n")
        bullet_notes = session_data.get('bullet_notes')
        if bullet_notes:
            for note in bullet_notes:
                f.write(f"- {note.replace('• ', '')}\n")
        else:
            f.write("Not available\n")
        f.write("\n")
        

        
        f.write("=== TRANSLATION ===\n")
        f.write((session_data.get('translated_content') or "Not available") + "\n\n")
        
        f.write("=== EXAM QUESTIONS ===\n")
        questions = session_data.get('questions', [])
        if questions:
            q_types = {'definition': 'Definitions', 'fill_blank': 'Fill in the Blanks', 'true_false': 'True or False'}
            for q_type, q_label in q_types.items():
                type_qs = [q for q in questions if q['type'] == q_type]
                if type_qs:
                    f.write(f"[{q_label}]\n")
                    for q in type_qs:
                        f.write(f"Q: {q['question']}\n")
                        f.write(f"A: {q['answer']}\n")
                    f.write("\n")
        else:
            f.write("Not available\n")
            
    return output_path

def generate_export(session_id: str, format: str, session_data: Dict[str, Any], exports_dir: str) -> str:
    """Routes the export request to the appropriate format generator."""
    valid_formats = ["pdf", "docx", "txt"]
    if format.lower() not in valid_formats:
        raise ValueError(f"Unsupported export format: {format}. Valid formats are: {', '.join(valid_formats)}")
    
    os.makedirs(exports_dir, exist_ok=True)
    filename = f"{session_id}_notes.{format.lower()}"
    output_path = os.path.join(exports_dir, filename)
    
    # If file exists, we could return it or regenerate. Requirements say "Return path".
    # I'll regenerate to ensure it's up to date with the latest session_data.
    
    if format.lower() == "pdf":
        return export_as_pdf(session_data, output_path)
    elif format.lower() == "docx":
        return export_as_docx(session_data, output_path)
    elif format.lower() == "txt":
        return export_as_txt(session_data, output_path)
    
    return output_path

def delete_exports(session_id: str):
    """Utility to delete all exports for a session (used by API)."""
    exports_dir = CONFIG.EXPORTS_FOLDER
    for fmt in ["pdf", "docx", "txt"]:
        path = os.path.join(exports_dir, f"{session_id}_notes.{fmt}")
        if os.path.exists(path):
            try:
                os.remove(path)
                logger.info(f"Deleted export: {path}")
            except Exception as e:
                logger.warning(f"Failed to delete export {path}: {e}")

# Note: The 'export_handler' singleton instance pattern from previous turn 
# is removed to follow the direct function signature requested.
